### ISSUE TITLE
Unexpected behaviour in query builder: using `where` after `and`

### ISSUE THREAD

**Issue by lavrukov** [ydb-platform/yoj-project#60]
I wrote this code and after it I spend an hour for detect a problem
```
    private TableQueryBuilder<Binding> getBindingsByTargetQuery(Binding.Type type, String target) {
        return db().BindingTable().query()
                .index(Binding.TYPE_TARGET_INDEX_NAME)
                .and("id.type").eq(type)
                .where("id.target").eq(target);
    }
```

The problem in `where` after `and`. This query will generate a filter `WHERE id_target = "$my_target"` without using id.type. This bug could be easy to get on copy-pasting.

It looks like this case should be uncompilable, or at least generate an exception.

**Comment by nvamelichev** [comment]
Making `where()` and `and()` do the same thing would be the easiest possible fix. You can then write, e.g.
```java
return db().bindings().query()
    .where("id.type").eq(type)
    .where("id.target").eq(target)
    .index(...)
    .limit(...)
    .find();
```

**Comment by nvamelichev** [comment]
@lavrukov Potential easy fix (making where() and and() mean the same thing): https://github.com/ydb-platform/yoj-project/pull/62
