### ISSUE TITLE
use the same default values for session pool as in ydb sdk

### ISSUE THREAD

**Issue by cardamo** [ydb-platform/yoj-project#92]
[sdk defaults](https://github.com/ydb-platform/ydb-java-sdk/blob/fe3af557f2deb8cde8887b40030abf67d3b78d12/table/src/main/java/tech/ydb/table/impl/pool/SessionPoolOptions.java#L11-L15) vs [yoj defaults](https://github.com/ydb-platform/yoj-project/blob/50a81f595f14ecca8c6cfe2df1b9cbfbce51917a/repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbConfig.java#L15-L20)

min pool size == 100 and max idle time == 5 minutes  - these values do not look like a reasonable default, I suggest having the same default values as in sdk

**Comment by nvamelichev** [comment]
Closing this as WONTFIX. Changing YOJ defaults has a high potential to cause damage, so short-term we fix it on our YOJ integration side. And in the long term, YOJ should be migrated to QueryService which has true session state checking to prevent exactly the same problems we were trying to mask by updating the defaults.
